In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [7]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.4790997 , 0.46489966, 0.24918813, 0.34922042, 0.55565008])

In [24]:
np.random.rand(5,5)

array([[0.51350698, 0.37882781, 0.58849828, 0.15218595, 0.03271301],
       [0.21760276, 0.63161568, 0.41319268, 0.37939988, 0.13628818],
       [0.85728594, 0.48595525, 0.0755669 , 0.73759346, 0.13894006],
       [0.69851362, 0.05529652, 0.96460787, 0.00964602, 0.93624319],
       [0.23181871, 0.28391712, 0.46085668, 0.31721888, 0.76202639]])

In [26]:
np.random.randn(4,4)

array([[ 0.11993795,  0.51330491, -1.41573695,  0.24506102],
       [ 0.36378611, -1.11287005, -0.04202222,  1.41472067],
       [ 0.0084765 , -0.96721642, -0.7514107 , -1.51266575],
       [-0.04351271, -0.6073752 ,  0.36349693, -1.07889398]])

In [28]:
np.random.randint(1,100,10)

array([38, 80, 75, 73, 18, 91, 28, 80, 20, 77])

In [31]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
rarr= np.random.randint(0,50,10)
rarr

array([10, 37, 20, 44, 35, 19, 47, 19, 12, 41])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
rarr.max()

47

In [36]:
rarr.min()

10

In [37]:
rarr.argmax()

6

In [38]:
rarr.argmin()

0

In [40]:
arr.shape

(25,)

In [43]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')