In [1]:
import numpy as np

In [22]:
# Array with array
arr = np.arange(0,11)
print(arr)

# Suma
suma = arr + arr

print(suma)

# Resta
resta = arr - arr

print(resta)

# Producto
prod = arr * arr

print(prod)

# Array con escalares
print(arr + 100)

print(arr - 100)

print(arr * 100)

# Potencias
print(arr ** 2)

# Raiz cuadrada
print(np.sqrt(arr))

# Exponencial
print(np.exp(arr))

# Max
print(np.max(arr))

print(arr.max())

# Sin and Cos
print(np.sin(arr))

print(np.cos(arr))

# Logaritmo
print(np.log(arr))


# WARNING

# Zero Division
print(arr / arr)

# Divided by Zero
print(1/arr)



[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]
[100 101 102 103 104 105 106 107 108 109 110]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
[   0  100  200  300  400  500  600  700  800  900 1000]
[  0   1   4   9  16  25  36  49  64  81 100]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
10
10
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.9459

c:\Users\desardi131\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:47: RuntimeWarning: divide by zero encountered in log
c:\Users\desardi131\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:53: RuntimeWarning: invalid value encountered in true_divide
c:\Users\desardi131\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:56: RuntimeWarning: divide by zero encountered in true_divide
